export const MELODIES = {
  TEST_HI_HAT: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  '-x-x-x-x-x-x-x-x',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----------------',
    HIGH_TOM:       '----------------',
    BASS:           '----------------',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 101,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Test HiHat',
  },
  TEST_SNARE: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  '----------------',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '-x-x-x-x-x-x-x-x',
    HIGH_TOM:       '----------------',
    BASS:           '----------------',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 101,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Test Snare',
  },
  TEST_BASS: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:   '----------------',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----------------',
    HIGH_TOM:       '----------------',
    BASS:           '-x-x-x-x-x-x-x-x',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 101,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Test Bass',
  },
  PUNK_1: {
    CRASH:          '--------',
    HI_HAT:         'x-x-x-x-',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x--x----',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 101,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Punk 1',
  },
  PUNK_2: {
    CRASH:          '--------',
    HI_HAT:         'x-x-x-x-',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x--x-x--',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 101,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Punk 2',
  },
  PUNK_3: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'x-x-x-x-',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           '-x-xx---',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 101,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Punk 3',
  },
  PUNK_4: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'x-x-x-x-',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'xx-xxx--',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 101,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Punk 4',
  },
  ROCK_1: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'x-x-x-x-',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x---x---',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 1',
  },
  ROCK_2: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'x-x-x-x-',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x-x-x-x-',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 2',
  },
  ROCK_3: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'x-x-x-x-',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x--xx---',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 3',
  },
  ROCK_4: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'x-x-x-x-',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x---xx--',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 4',
  },
  ROCKABILLY_1: {
    CRASH:          '--------',
    HI_HAT:         'x-x-x-x-',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x---x---',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 108,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rockabilly 1',
  },
  ROCKABILLY_2: {
    CRASH:          '--------',
    HI_HAT:         'x-x-x-x-',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x-x-x-x-',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 108,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rockabilly 2',
  },
  ROCKABILLY_3: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  '----------------',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x-----x-x-------',
    MEDIUM_TOM:     '----------------',
    RIDE:           'x---x-x-x---x-x-',
    FLOOR_TOM:      '----------------',
    SPEED: 94,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rockabilly 3',
  },
  ROCK_N_ROLL_B_1: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'x-x-x-x-x-x-x-x-',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x-------x-x---x-',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 180,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rock & Roll B1',
  },
  ROCK_N_ROLL_B_2: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'x-x-x-x-x-x-x-x-',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x-----x---x---x-',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 180,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rock & Roll B2',
  },
  ROCK_N_ROLL_B_3: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'x-x-x-x-x-x-x-x-',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-x-----x---',
    HIGH_TOM:       '----------------',
    BASS:           'x---------x-----',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 144,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rock & Roll B3',
  },
  ROCK_8THS_1: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'xxxxxxxx',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x---x--x',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 8ths 1',
  },
  ROCK_8THS_2: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'xxxxxxxx',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'xx--xx--',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 8ths 2',
  },
  ROCK_8THS_3: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'xxxxxxxx',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'xx-xx---',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 8ths 3',
  },
  ROCK_8THS_4: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'xxxxxxxx',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'xx-x-x--',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 8ths 4',
  },
  ROCK_SLOW_16THS_1: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxxxxxx',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x-----x-x-------',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 80,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rock Slow 16ths 1',
  },
  ROCK_SLOW_16THS_2: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxxxxxx',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x------xx-------',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 80,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rock Slow 16ths 2',
  },
  ROCK_SLOW_16THS_3: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxxxxxx',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x------xx-x-----',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 80,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rock Slow 16ths 3',
  },
  ROCK_SLOW_16THS_4: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxxxxxx',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x------xx-----x-',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 80,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rock Slow 16ths 4',
  },
  ROCK_SLOW_12_8_1: {
    CRASH:          '------------',
    HI_HAT:         '------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxx',
    HI_HAT_PEDAL:   '------------',
    SNARE:          '---x-----x--',
    HIGH_TOM:       '------------',
    BASS:           'x-----x-----',
    MEDIUM_TOM:     '------------',
    RIDE:           '------------',
    FLOOR_TOM:      '------------',
    SPEED: 60,
    TACT: () => 12 / 8,
    STEPS: 12,
    NAME: 'Rock Slow 12/8 1',
  },
  ROCK_SLOW_12_8_2: {
    CRASH:          '------------',
    HI_HAT:         '------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxx',
    HI_HAT_PEDAL:   '------------',
    SNARE:          '---x-----x--',
    HIGH_TOM:       '------------',
    BASS:           'x----xx-----',
    MEDIUM_TOM:     '------------',
    RIDE:           '------------',
    FLOOR_TOM:      '------------',
    SPEED: 60,
    TACT: () => 12 / 8,
    STEPS: 12,
    NAME: 'Rock Slow 12/8 2',
  },
  ROCK_SLOW_12_8_3: {
    CRASH:          '------------',
    HI_HAT:         '------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxx',
    HI_HAT_PEDAL:   '------------',
    SNARE:          '---x-----x--',
    HIGH_TOM:       '------------',
    BASS:           'x----xx----x',
    MEDIUM_TOM:     '------------',
    RIDE:           '------------',
    FLOOR_TOM:      '------------',
    SPEED: 60,
    TACT: () => 12 / 8,
    STEPS: 12,
    NAME: 'Rock Slow 12/8 3',
  },
  ROCK_SLOW_12_8_4: {
    CRASH:          '------------',
    HI_HAT:         '------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxx',
    HI_HAT_PEDAL:   '------------',
    SNARE:          '---x-----x--',
    HIGH_TOM:       '------------',
    BASS:           'x-x--xx-----',
    MEDIUM_TOM:     '------------',
    RIDE:           '------------',
    FLOOR_TOM:      '------------',
    SPEED: 60,
    TACT: () => 12 / 8,
    STEPS: 12,
    NAME: 'Rock Slow 12/8 4',
  },
  ALT_ROCK_1: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'x-x-x-x-x-x-x-x-',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x------x--x-',
    HIGH_TOM:       '----------------',
    BASS:           'x-x-----x---x---',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 112,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Alt Rock 1',
  },
  BEACH_MUSIC_A_1: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--xx--x-',
    HIGH_TOM:       '--------',
    BASS:           'x---x---',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      'xxxxxxxx',
    SPEED: 65,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Beach Music A 1',
  },
  BEACH_MUSIC_A_2: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--xx--x-',
    HIGH_TOM:       '--------',
    BASS:           'x---x---',
    MEDIUM_TOM:     '--------',
    RIDE:           'xxxxxxxx',
    FLOOR_TOM:      '--------',
    SPEED: 65,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Beach Music A 2',
  },
  BEACH_MUSIC_A_3: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x--xx---',
    MEDIUM_TOM:     '--------',
    RIDE:           'xxxxxxxx',
    FLOOR_TOM:      '--------',
    SPEED: 65,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Beach Music A 3',
  },
  BOOGIE_WOOGIE_1: {
    CRASH:          '----------------',
    HI_HAT:         '----x-------x---',
    HI_HAT_CLOSED:  'xx---x--xx---x--',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '-----x-------x--',
    HIGH_TOM:       '----------------',
    BASS:           'xx--x---xx--x---',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 146,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Boogie Woogie 1',
  },
  BOOGIE_WOOGIE_2: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  '----------------',
    HI_HAT_PEDAL:   'x---x---x---x---',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x--x---xx--x---x',
    MEDIUM_TOM:     '----------------',
    RIDE:           'x--xx--xx--xx--x',
    FLOOR_TOM:      '----------------',
    SPEED: 146,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Boogie Woogie 2',
  },
}
