export const MELODIES = {
  PUNK_1: {
    CRASH:          '--------',
    HI_HAT:         'x-x-x-x-',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x--x----',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 101,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Punk 1',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Punk 1.png',
    DIFFICULTY: "easy",
  },
  PUNK_2: {
    CRASH:          '--------',
    HI_HAT:         'x-x-x-x-',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x--x-x--',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 101,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Punk 2',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Punk 2.png',
    DIFFICULTY: "easy"
  },
  PUNK_3: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'x-x-x-x-',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           '-x-xx---',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 101,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Punk 3',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Punk 3.png',
    DIFFICULTY: "medium",
  },
  PUNK_4: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'x-x-x-x-',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'xx-xxx--',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 101,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Punk 4',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Punk 4.png',
    DIFFICULTY: "medium",
  },
  ROCK_1: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'x-x-x-x-',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x---x---',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 1',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock 1.png',
    DIFFICULTY: "very easy",
  },
  ROCK_2: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'x-x-x-x-',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x-x-x-x-',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 2',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock 2.png',
    DIFFICULTY: "very easy",
  },
  ROCK_3: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'x-x-x-x-',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x--xx---',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 3',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock 3.png',
    DIFFICULTY: "easy",
  },
  ROCK_4: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'x-x-x-x-',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x---xx--',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 4',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock 4.png',
    DIFFICULTY: "easy",
  },
  ROCKABILLY_1: {
    CRASH:          '--------',
    HI_HAT:         'x-x-x-x-',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x---x---',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 108,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rockabilly 1',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rockabilly 1.png',
    DIFFICULTY: "very easy",
  },
  ROCKABILLY_2: {
    CRASH:          '--------',
    HI_HAT:         'x-x-x-x-',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x-x-x-x-',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 108,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rockabilly 2',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rockabilly 2.png',
    DIFFICULTY: "very easy",
  },
  ROCKABILLY_3: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  '----------------',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x-----x-x-------',
    MEDIUM_TOM:     '----------------',
    RIDE:           'x---x-x-x---x-x-',
    FLOOR_TOM:      '----------------',
    SPEED: 94,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rockabilly 3',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rockabilly 3.png',
    DIFFICULTY: "easy",
  },
  ROCK_N_ROLL_B_1: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'x-x-x-x-x-x-x-x-',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x-------x-x---x-',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 180,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rock & Roll B1',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock & Roll B 1.png',
    DIFFICULTY: "medium",
  },
  ROCK_N_ROLL_B_2: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'x-x-x-x-x-x-x-x-',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x-----x---x---x-',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 180,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rock & Roll B2',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock & Roll B 2.png',
    DIFFICULTY: "medium",
  },
  ROCK_N_ROLL_B_3: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'x-x-x-x-x-x-x-x-',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-x-----x---',
    HIGH_TOM:       '----------------',
    BASS:           'x---------x-----',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 144,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rock & Roll B3',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock & Roll B 3.png',
    DIFFICULTY: "easy",
  },
  ROCK_8THS_1: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'xxxxxxxx',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x---x--x',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 8ths 1',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock 8ths 1.png',
    DIFFICULTY: "easy",
  },
  ROCK_8THS_2: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'xxxxxxxx',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'xx--xx--',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 8ths 2',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock 8ths 2.png',
    DIFFICULTY: "easy",
  },
  ROCK_8THS_3: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'xxxxxxxx',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'xx-xx---',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 8ths 3',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock 8ths 3.png',
    DIFFICULTY: "easy",
  },
  ROCK_8THS_4: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  'xxxxxxxx',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'xx-x-x--',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 66,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Rock 8ths 4',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock 8ths 4.png',
    DIFFICULTY: "easy",
  },
  ROCK_SLOW_16THS_1: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxxxxxx',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x-----x-x-------',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 80,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rock Slow 16ths 1',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock Slow 16ths 1.png',
    DIFFICULTY: "medium",
  },
  ROCK_SLOW_16THS_2: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxxxxxx',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x------xx-------',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 80,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rock Slow 16ths 2',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock Slow 16ths 2.png',
    DIFFICULTY: "medium",
  },
  ROCK_SLOW_16THS_3: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxxxxxx',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x------xx-x-----',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 80,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rock Slow 16ths 3',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock Slow 16ths 3.png',
    DIFFICULTY: "medium",
  },
  ROCK_SLOW_16THS_4: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxxxxxx',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x------xx-----x-',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 80,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Rock Slow 16ths 4',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock Slow 16ths 4.png',
    DIFFICULTY: "medium",
  },
  ROCK_SLOW_12_8_1: {
    CRASH:          '------------',
    HI_HAT:         '------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxx',
    HI_HAT_PEDAL:   '------------',
    SNARE:          '---x-----x--',
    HIGH_TOM:       '------------',
    BASS:           'x-----x-----',
    MEDIUM_TOM:     '------------',
    RIDE:           '------------',
    FLOOR_TOM:      '------------',
    SPEED: 60,
    TACT: () => 12 / 8,
    STEPS: 12,
    NAME: 'Rock Slow 12/8 1',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock Slow 12-8 1.png',
    DIFFICULTY: "easy",
  },
  ROCK_SLOW_12_8_2: {
    CRASH:          '------------',
    HI_HAT:         '------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxx',
    HI_HAT_PEDAL:   '------------',
    SNARE:          '---x-----x--',
    HIGH_TOM:       '------------',
    BASS:           'x----xx-----',
    MEDIUM_TOM:     '------------',
    RIDE:           '------------',
    FLOOR_TOM:      '------------',
    SPEED: 60,
    TACT: () => 12 / 8,
    STEPS: 12,
    NAME: 'Rock Slow 12/8 2',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock Slow 12-8 2.png',
    DIFFICULTY: "easy",
  },
  ROCK_SLOW_12_8_3: {
    CRASH:          '------------',
    HI_HAT:         '------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxx',
    HI_HAT_PEDAL:   '------------',
    SNARE:          '---x-----x--',
    HIGH_TOM:       '------------',
    BASS:           'x----xx----x',
    MEDIUM_TOM:     '------------',
    RIDE:           '------------',
    FLOOR_TOM:      '------------',
    SPEED: 60,
    TACT: () => 12 / 8,
    STEPS: 12,
    NAME: 'Rock Slow 12/8 3',
    IMAGE: 'Rock-Rock Slow 12-8 3.png',
    DIFFICULTY: "easy",
  },
  ROCK_SLOW_12_8_4: {
    CRASH:          '------------',
    HI_HAT:         '------------',
    HI_HAT_CLOSED:  'xxxxxxxxxxxx',
    HI_HAT_PEDAL:   '------------',
    SNARE:          '---x-----x--',
    HIGH_TOM:       '------------',
    BASS:           'x-x--xx-----',
    MEDIUM_TOM:     '------------',
    RIDE:           '------------',
    FLOOR_TOM:      '------------',
    SPEED: 60,
    TACT: () => 12 / 8,
    STEPS: 12,
    NAME: 'Rock Slow 12/8 4',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Rock Slow 12-8 4.png',
    DIFFICULTY: "medium",
  },
  ALT_ROCK_1: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  'x-x-x-x-x-x-x-x-',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '----x------x--x-',
    HIGH_TOM:       '----------------',
    BASS:           'x-x-----x---x---',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 112,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Alt Rock 1',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Alt Rock 1.png',
    DIFFICULTY: "medium",
  },
  BEACH_MUSIC_A_1: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--xx--x-',
    HIGH_TOM:       '--------',
    BASS:           'x---x---',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      'xxxxxxxx',
    SPEED: 65,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Beach Music A 1',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Beach Music A 1.png',
    DIFFICULTY: "medium",
  },
  BEACH_MUSIC_A_2: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--xx--x-',
    HIGH_TOM:       '--------',
    BASS:           'x---x---',
    MEDIUM_TOM:     '--------',
    RIDE:           'xxxxxxxx',
    FLOOR_TOM:      '--------',
    SPEED: 65,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Beach Music A 2',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Beach Music A 2.png',
    DIFFICULTY: "medium",
  },
  BEACH_MUSIC_A_3: {
    CRASH:          '--------',
    HI_HAT:         '--------',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x--xx---',
    MEDIUM_TOM:     '--------',
    RIDE:           'xxxxxxxx',
    FLOOR_TOM:      '--------',
    SPEED: 65,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Beach Music A 3',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Beach Music A 3.png',
    DIFFICULTY: "medium",
  },
  BOOGIE_WOOGIE_1: {
    CRASH:          '----------------',
    HI_HAT:         '----x-------x---',
    HI_HAT_CLOSED:  'xx---x--xx---x--',
    HI_HAT_PEDAL:   '----------------',
    SNARE:          '-----x-------x--',
    HIGH_TOM:       '----------------',
    BASS:           'xx--x---xx--x---',
    MEDIUM_TOM:     '----------------',
    RIDE:           '----------------',
    FLOOR_TOM:      '----------------',
    SPEED: 146,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Boogie Woogie 1',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Boogie-Woogie 1.png',
    DIFFICULTY: "medium",
  },
  BOOGIE_WOOGIE_2: {
    CRASH:          '----------------',
    HI_HAT:         '----------------',
    HI_HAT_CLOSED:  '----------------',
    HI_HAT_PEDAL:   'x---x---x---x---',
    SNARE:          '----x-------x---',
    HIGH_TOM:       '----------------',
    BASS:           'x--x---xx--x---x',
    MEDIUM_TOM:     '----------------',
    RIDE:           'x--xx--xx--xx--x',
    FLOOR_TOM:      '----------------',
    SPEED: 146,
    TACT: () => 4 / 4,
    STEPS: 16,
    NAME: 'Boogie Woogie 2',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Boogie-Woogie 2.png',
    DIFFICULTY: "medium",
  },
  HEAVY_METAL_A_1: {
    CRASH:          '--------',
    HI_HAT:         'x-x-x-x-',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'x--x-x--',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 115,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Heavy Metal A 1',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Heavy Metal A 1.png',
    DIFFICULTY: "easy",
  },
  HEAVY_METAL_A_2: {
    CRASH:          '--------',
    HI_HAT:         'x-x-x-x-',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'xx-x-x--',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 115,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Heavy Metal A 2',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Heavy Metal A 2.png',
    DIFFICULTY: "medium",
  },
  HEAVY_METAL_A_3: {
    CRASH:          '--------',
    HI_HAT:         'x-x-x-x-',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'xx--xx--',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 135,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Heavy Metal A 3',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Heavy Metal A 3.png',
    DIFFICULTY: "medium",
  },
  HEAVY_METAL_A_4: {
    CRASH:          '--------',
    HI_HAT:         'x-x-x-x-',
    HI_HAT_CLOSED:  '--------',
    HI_HAT_PEDAL:   '--------',
    SNARE:          '--x---x-',
    HIGH_TOM:       '--------',
    BASS:           'xxxxxxxx',
    MEDIUM_TOM:     '--------',
    RIDE:           '--------',
    FLOOR_TOM:      '--------',
    SPEED: 85,
    TACT: () => 4 / 4,
    STEPS: 8,
    NAME: 'Heavy Metal A 4',
    CATEGORY: "Rock",
    IMAGE: 'Rock-Heavy Metal A 4.png',
    DIFFICULTY: "easy",
  },
  BLUES_SLOW_1: {
    CRASH:          '------------',
    HI_HAT:         'xxxxxxxxxxxx',
    HI_HAT_CLOSED:  '------------',
    HI_HAT_PEDAL:   '------------',
    SNARE:          '---x-----x--',
    HIGH_TOM:       '------------',
    BASS:           'x-----x-----',
    MEDIUM_TOM:     '------------',
    RIDE:           '------------',
    FLOOR_TOM:      '------------',
    SPEED: 39,
    TACT: () => 4 / 4,
    STEPS: 12,
    NAME: 'Blues Slow 1',
    CATEGORY: "Blues",
    IMAGE: 'Blues-Blues Slow 1.png',
    DIFFICULTY: "easy",
  },
  BLUES_SLOW_2: {
    CRASH:          '------------',
    HI_HAT:         'xxxxxxxxxxxx',
    HI_HAT_CLOSED:  '------------',
    HI_HAT_PEDAL:   '------------',
    SNARE:          '---x-----x--',
    HIGH_TOM:       '------------',
    BASS:           'x----xx-----',
    MEDIUM_TOM:     '------------',
    RIDE:           '------------',
    FLOOR_TOM:      '------------',
    SPEED: 39,
    TACT: () => 4 / 4,
    STEPS: 12,
    NAME: 'Blues Slow 2',
    CATEGORY: "Blues",
    IMAGE: 'Blues-Blues Slow 2.png',
    DIFFICULTY: "easy",
  },
  BLUES_SLOW_3: {
    CRASH:          '------------',
    HI_HAT:         '------------',
    HI_HAT_CLOSED:  '------------',
    HI_HAT_PEDAL:   '------------',
    SNARE:          '---x-----x--',
    HIGH_TOM:       '------------',
    BASS:           'x-x--xx-x---',
    MEDIUM_TOM:     '------------',
    RIDE:           'xxxxxxxxxxxx',
    FLOOR_TOM:      '------------',
    SPEED: 39,
    TACT: () => 4 / 4,
    STEPS: 12,
    NAME: 'Blues Slow 3',
    CATEGORY: "Blues",
    IMAGE: 'Blues-Blues Slow 3.png',
    DIFFICULTY: "medium",
  }
}
